name: portfolio
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter    
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_strategy: ^0.2.0
  responsive_builder: ^0.7.0
  flutter_animate: ^4.5.0
  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.2.2
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.2.6
  scrollable_positioned_list:
    git:
      url: https://github.com/nabil6391/flutter.widgets.git
      ref: master
      path: packages/scrollable_positioned_list/
 
  full_screen_image: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  carousel_slider: ^5.0.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter_launcher_icons:
  android: true
  image_path: "assets/images/applogo1.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/project_banners/
  

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/montserrat.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Light.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic


